# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Benjamin #Barton, Ph.D.
description: A collection of the projects I've been working on... ‚ù§
github_username: benbardev

# Email and twitter are optional:
email:
twitter_username:
linkedin_username: ben-barton-dev
linkedin_url: "https://www.linkedin.com/in/ben-barton-dev/"

minima:
    social_links:
    - { platform: github,  user_url: "https://github.com/benbardev" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ben-barton-dev/" }
    - { platform: google_scholar, user_url: "https://scholar.google.fr/citations?user=h93xgqMAAAAJ&hl=en" }
#    - { platform: orcid, user_url: "https://www.orcid.org/0000-0001-9998-2064" }

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

header_pages:
  - projects.md
  - publications.md
  - cv.md

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
