# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Benjamin Barton, Ph.D.
description: A collection of the projects I've been working on... ‚ù§
github_username: benbardev

# Email and twitter are optional:
email:
twitter_username:

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

header_pages:
  - projects.md
  - pubs.md
  - cv.md

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
